#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                          0
#define TRAINER_AARON                         1
#define TRAINER_ABIGAIL_1                     2
#define TRAINER_ABIGAIL_2                     3
#define TRAINER_ABIGAIL_3                     4
#define TRAINER_AIDAN                         5
#define TRAINER_AISHA                         6
#define TRAINER_ALAN                          7
#define TRAINER_ALBERT                        8
#define TRAINER_ALBERTO                       9
#define TRAINER_ALEX                         10
#define TRAINER_ALEXA                        11
#define TRAINER_ALEXIA                       12
#define TRAINER_ALEXIS                       13
#define TRAINER_ALICE                        14
#define TRAINER_ALIX                         15
#define TRAINER_ALLEN                        16
#define TRAINER_ALLISON                      17
#define TRAINER_ALVARO                       18
#define TRAINER_ALYSSA                       19
#define TRAINER_AMY_AND_LIV_1                20
#define TRAINER_AMY_AND_LIV_2                21
#define TRAINER_AMY_AND_LIV_3                22
#define TRAINER_ANABEL                       23
#define TRAINER_ANDREA                       24
#define TRAINER_ANDRES_1                     25
#define TRAINER_ANDRES_2                     26
#define TRAINER_ANDRES_3                     27
#define TRAINER_ANDREW                       28
#define TRAINER_ANGELICA                     29
#define TRAINER_ANGELINA                     30
#define TRAINER_ANGELO                       31
#define TRAINER_ANNA_AND_MEG_1               32
#define TRAINER_ANNA_AND_MEG_2               33
#define TRAINER_ANNA_AND_MEG_3               34
#define TRAINER_ANNIKA                       35
#define TRAINER_ANTHONY                      36
#define TRAINER_ASHLEY                       37
#define TRAINER_ATHENA                       38
#define TRAINER_ATSUSHI                      39
#define TRAINER_AURON                        40
#define TRAINER_AUSTINA                      41
#define TRAINER_AUTUMN                       42
#define TRAINER_AXLE                         43
#define TRAINER_BARNY                        44
#define TRAINER_BARRY                        45
#define TRAINER_BEAU                         46
#define TRAINER_BECK                         47
#define TRAINER_BECKY                        48
#define TRAINER_BEN                          49
#define TRAINER_BENJAMIN_1                   50
#define TRAINER_BENJAMIN_2                   51
#define TRAINER_BENJAMIN_3                   52
#define TRAINER_BENNY                        53
#define TRAINER_BERKE                        54
#define TRAINER_BERNIE_1                     55
#define TRAINER_BERNIE_2                     56
#define TRAINER_BERNIE_3                     57
#define TRAINER_BETH                         58
#define TRAINER_BETHANY                      59
#define TRAINER_BEVERLY                      60
#define TRAINER_BIANCA                       61
#define TRAINER_BILLY                        62
#define TRAINER_BLAKE                        63
#define TRAINER_BRANDEN                      64
#define TRAINER_BRANDI                       65
#define TRAINER_BRANDON                      66
#define TRAINER_BRAXTON                      67
#define TRAINER_BRENDA                       68
#define TRAINER_BRENDEN                      69
#define TRAINER_BRENT                        70
#define TRAINER_BRIANNA                      71
#define TRAINER_BRICE                        72
#define TRAINER_BRIDGET                      73
#define TRAINER_BROOKE_1                     74
#define TRAINER_BROOKE_2                     75
#define TRAINER_BROOKE_3                     76
#define TRAINER_BRYAN                        77
#define TRAINER_BRYANT                       78
#define TRAINER_CALE                         79
#define TRAINER_CALLIE                       80
#define TRAINER_CALVIN_1                     81
#define TRAINER_CALVIN_2                     82
#define TRAINER_CALVIN_3                     83
#define TRAINER_CAMDEN                       84
#define TRAINER_CAMERON_1                    85
#define TRAINER_CAMERON_2                    86
#define TRAINER_CAMERON_3                    87
#define TRAINER_CAMRON                       88
#define TRAINER_CARLEE                       89
#define TRAINER_CAROL                        90
#define TRAINER_CAROLINA                     91
#define TRAINER_CAROLINE                     92
#define TRAINER_CARTER                       93
#define TRAINER_CATHERINE_1                  94
#define TRAINER_CATHERINE_2                  95
#define TRAINER_CATHERINE_3                  96
#define TRAINER_CEDRIC                       97
#define TRAINER_CELIA                        98
#define TRAINER_CELINA                       99
#define TRAINER_CHAD                        100
#define TRAINER_CHANDLER                    101
#define TRAINER_CHARLIE                     102
#define TRAINER_CHARLOTTE                   103
#define TRAINER_CHASE                       104
#define TRAINER_CHESTER                     105
#define TRAINER_CHIP                        106
#define TRAINER_CHRIS                       107
#define TRAINER_CINDY_1                     108
#define TRAINER_CINDY_2                     109
#define TRAINER_CINDY_3                     110
#define TRAINER_CLARENCE                    111
#define TRAINER_CLARISSA                    112
#define TRAINER_CLARK                       113
#define TRAINER_CLAUDE                      114
#define TRAINER_CLIFFORD                    115
#define TRAINER_COBY                        116
#define TRAINER_COLE                        117
#define TRAINER_COLIN                       118
#define TRAINER_COLTON                      119
#define TRAINER_CONNIE                      120
#define TRAINER_CONOR                       121
#define TRAINER_CORA                        122
#define TRAINER_CORY_1                      123
#define TRAINER_CORY_2                      124
#define TRAINER_CORY_3                      125
#define TRAINER_CRISSY                      126
#define TRAINER_CRISTIAN                    127
#define TRAINER_CRISTIN_1                   128
#define TRAINER_CRISTIN_2                   129
#define TRAINER_CRISTIN_3                   130
#define TRAINER_CYNDY_1                     131
#define TRAINER_CYNDY_2                     132
#define TRAINER_CYNDY_3                     133
#define TRAINER_DAISUKE                     134
#define TRAINER_DAISY                       135
#define TRAINER_DALE                        136
#define TRAINER_DALTON_1                    137
#define TRAINER_DALTON_2                    138
#define TRAINER_DALTON_3                    139
#define TRAINER_DANA                        140
#define TRAINER_DANIELLE                    141
#define TRAINER_DAPHNE                      142
#define TRAINER_DARCY                       143
#define TRAINER_DARIAN                      144
#define TRAINER_DARIUS                      145
#define TRAINER_DARRIN                      146
#define TRAINER_DAVID                       147
#define TRAINER_DAVIS                       148
#define TRAINER_DAWSON                      149
#define TRAINER_DAYTON                      150
#define TRAINER_DEAN                        151
#define TRAINER_DEANDRE                     152
#define TRAINER_DEBRA                       153
#define TRAINER_DECLAN                      154
#define TRAINER_DEMETRIUS                   155
#define TRAINER_DENISE                      156
#define TRAINER_DEREK                       157
#define TRAINER_DEVAN                       158
#define TRAINER_DEZ_AND_LUKE                159
#define TRAINER_DIANA_1                     160
#define TRAINER_DIANA_2                     161
#define TRAINER_DIANA_3                     162
#define TRAINER_DIANNE                      163
#define TRAINER_DILLON                      164
#define TRAINER_DOMINIK                     165
#define TRAINER_DONALD                      166
#define TRAINER_DONNY                       167
#define TRAINER_DOUG                        168
#define TRAINER_DOUGLAS                     169
#define TRAINER_DREW                        170
#define TRAINER_DUDLEY                      171
#define TRAINER_DUNCAN                      172
#define TRAINER_DUSTY_1                     173
#define TRAINER_DUSTY_2                     174
#define TRAINER_DUSTY_3                     175
#define TRAINER_DWAYNE                      176
#define TRAINER_DYLAN_1                     177
#define TRAINER_DYLAN_2                     178
#define TRAINER_DYLAN_3                     179
#define TRAINER_ED                          180
#define TRAINER_EDDIE                       181
#define TRAINER_EDGAR                       182
#define TRAINER_EDMOND                      183
#define TRAINER_EDWARD                      184
#define TRAINER_EDWARDO                     185
#define TRAINER_EDWIN_1                     186
#define TRAINER_EDWIN_2                     187
#define TRAINER_EDWIN_3                     188
#define TRAINER_ELI                         189
#define TRAINER_ELIJAH                      190
#define TRAINER_ELLIOT_1                    191
#define TRAINER_ELLIOT_2                    192
#define TRAINER_ELLIOT_3                    193
#define TRAINER_ERIC                        194
#define TRAINER_ERNEST_1                    195
#define TRAINER_ERNEST_2                    196
#define TRAINER_ERNEST_3                    197
#define TRAINER_ETHAN_1                     198
#define TRAINER_ETHAN_2                     199
#define TRAINER_ETHAN_3                     200
#define TRAINER_EVERETT                     201
#define TRAINER_FABIAN                      202
#define TRAINER_FELIX                       203
#define TRAINER_FERNANDO_1                  204
#define TRAINER_FERNANDO_2                  205
#define TRAINER_FERNANDO_3                  206
#define TRAINER_FLINT                       207
#define TRAINER_FOSTER                      208
#define TRAINER_FRANKLIN                    209
#define TRAINER_FREDRICK                    210
#define TRAINER_GABRIELLE_1                 211
#define TRAINER_GABRIELLE_2                 212
#define TRAINER_GABRIELLE_3                 213
#define TRAINER_GARRET                      214
#define TRAINER_GARRISON                    215
#define TRAINER_GEORGE                      216
#define TRAINER_GEORGIA                     217
#define TRAINER_GERALD                      218
#define TRAINER_GILBERT                     219
#define TRAINER_GINA_AND_MIA_1              220
#define TRAINER_GRACE                       221
#define TRAINER_GREG                        222
#define TRAINER_GRETA                       223
#define TRAINER_GWEN                        224
#define TRAINER_HAILEY                      225
#define TRAINER_HALEY_1                     226
#define TRAINER_HALEY_2                     227
#define TRAINER_HALEY_3                     228
#define TRAINER_HALLE                       229
#define TRAINER_HANNAH                      230
#define TRAINER_HARRISON                    231
#define TRAINER_HAYDEN                      232
#define TRAINER_HECTOR                      233
#define TRAINER_HEIDI                       234
#define TRAINER_HELENE                      235
#define TRAINER_HENRY                       236
#define TRAINER_HERMAN                      237
#define TRAINER_HIDEO                       238
#define TRAINER_HITOSHI                     239
#define TRAINER_HOPE                        240
#define TRAINER_HUDSON                      241
#define TRAINER_HUEY                        242
#define TRAINER_HUGH                        243
#define TRAINER_HUMBERTO                    244
#define TRAINER_IMANI                       245
#define TRAINER_IRENE                       246
#define TRAINER_ISAAC_1                     247
#define TRAINER_ISAAC_2                     248
#define TRAINER_ISAAC_3                     249
#define TRAINER_ISABELLA                    250
#define TRAINER_ISABELLE                    251
#define TRAINER_ISABEL_1                    252
#define TRAINER_ISABEL_2                    253
#define TRAINER_ISABEL_3                    254
#define TRAINER_ISAIAH_1                    255
#define TRAINER_ISAIAH_2                    256
#define TRAINER_ISAIAH_3                    257
#define TRAINER_ISOBEL                      258
#define TRAINER_IVAN                        259
#define TRAINER_JACE                        260
#define TRAINER_JACK                        261
#define TRAINER_JACKI_1                     262
#define TRAINER_JACKI_2                     263
#define TRAINER_JACKI_3                     264
#define TRAINER_JACKSON_1                   265
#define TRAINER_JACKSON_2                   266
#define TRAINER_JACKSON_3                   267
#define TRAINER_JACLYN                      268
#define TRAINER_JACOB                       269
#define TRAINER_JAIDEN                      270
#define TRAINER_JAMES_1                     271
#define TRAINER_JAMES_2                     272
#define TRAINER_JAMES_3                     273
#define TRAINER_JANI                        274
#define TRAINER_JANICE                      275
#define TRAINER_JARED                       276
#define TRAINER_JASMINE                     277
#define TRAINER_JAYLEN                      278
#define TRAINER_JAZMYN                      279
#define TRAINER_JEFF                        280
#define TRAINER_JEFFREY_1                   281
#define TRAINER_JEFFREY_2                   282
#define TRAINER_JEFFREY_3                   283
#define TRAINER_JENNA                       284
#define TRAINER_JENNIFER                    285
#define TRAINER_JENNY_1                     286
#define TRAINER_JENNY_2                     287
#define TRAINER_JENNY_3                     288
#define TRAINER_JEROME                      289
#define TRAINER_JERRY_1                     290
#define TRAINER_JERRY_2                     291
#define TRAINER_JERRY_3                     292
#define TRAINER_JESSICA_1                   293
#define TRAINER_JESSICA_2                   294
#define TRAINER_JESSICA_3                   295
#define TRAINER_JOCELYN                     296
#define TRAINER_JODY                        297
#define TRAINER_JOEY                        298
#define TRAINER_JOHANNA                     299
#define TRAINER_JOHNSON                     300
#define TRAINER_JOHN_AND_JAY_1              301
#define TRAINER_JOHN_AND_JAY_2              302
#define TRAINER_JOHN_AND_JAY_3              303
#define TRAINER_JONAH                       304
#define TRAINER_JONAS                       305
#define TRAINER_JONATHAN                    306
#define TRAINER_JOSE                        307
#define TRAINER_JOSEPH                      308
#define TRAINER_JOSH                        309
#define TRAINER_JOSHUA                      310
#define TRAINER_JOSUE                       311
#define TRAINER_JULIE                       312
#define TRAINER_JULIO                       313
#define TRAINER_JUSTIN                      314
#define TRAINER_KAI                         315
#define TRAINER_KALEB                       316
#define TRAINER_KARA                        317
#define TRAINER_KAREN_1                     318
#define TRAINER_KAREN_2                     319
#define TRAINER_KAREN_3                     320
#define TRAINER_KATELYNN                    321
#define TRAINER_KATELYN_1                   322
#define TRAINER_KATELYN_2                   323
#define TRAINER_KATELYN_3                   324
#define TRAINER_KATE_AND_JOY                325
#define TRAINER_KATHLEEN                    326
#define TRAINER_KATIE                       327
#define TRAINER_KAYLA                       328
#define TRAINER_KAYLEE                      329
#define TRAINER_KAYLEY                      330
#define TRAINER_KEEGAN                      331
#define TRAINER_KEIGO                       332
#define TRAINER_KEIRA                       333
#define TRAINER_KELVIN                      334
#define TRAINER_KENT                        335
#define TRAINER_KEVIN                       336
#define TRAINER_KIM_AND_IRIS                337
#define TRAINER_KINDRA                      338
#define TRAINER_KIRA_AND_DAN_1              339
#define TRAINER_KIRA_AND_DAN_2              340
#define TRAINER_KIRA_AND_DAN_3              341
#define TRAINER_KIRK                        342
#define TRAINER_KIYO                        343
#define TRAINER_KOICHI                      344
#define TRAINER_KOJI_1                      345
#define TRAINER_KOJI_2                      346
#define TRAINER_KOJI_3                      347
#define TRAINER_KYLA                        348
#define TRAINER_KYRA                        349
#define TRAINER_LAO_1                       350
#define TRAINER_LAO_2                       351
#define TRAINER_LAO_3                       352
#define TRAINER_LARRY                       353
#define TRAINER_LAURA                       354
#define TRAINER_LAUREL                      355
#define TRAINER_LAWRENCE                    356
#define TRAINER_LEAH                        357
#define TRAINER_LEA_AND_JED                 358
#define TRAINER_LENNY                       359
#define TRAINER_LEONARD                     360
#define TRAINER_LEONARDO                    361
#define TRAINER_LEONEL                      362
#define TRAINER_LEROY                       363
#define TRAINER_LILA_AND_ROY_1              364
#define TRAINER_LILA_AND_ROY_2              365
#define TRAINER_LILA_AND_ROY_3              366
#define TRAINER_LILITH                      367
#define TRAINER_LINDA                       368
#define TRAINER_LISA_AND_RAY                369
#define TRAINER_LOLA_1                      370
#define TRAINER_LOLA_2                      371
#define TRAINER_LOLA_3                      372
#define TRAINER_LORENZO                     373
#define TRAINER_LUCAS_1                     374
#define TRAINER_LUCY                        375
#define TRAINER_LUIS                        376
#define TRAINER_LUNG                        377
#define TRAINER_LYDIA_1                     378
#define TRAINER_LYDIA_2                     379
#define TRAINER_LYDIA_3                     380
#define TRAINER_LYLE                        381
#define TRAINER_MACEY                       382
#define TRAINER_MADELINE_1                  383
#define TRAINER_MADELINE_2                  384
#define TRAINER_MADELINE_3                  385
#define TRAINER_MAKAYLA                     386
#define TRAINER_MARC                        387
#define TRAINER_MARCEL                      388
#define TRAINER_MARCOS                      389
#define TRAINER_MARIA_1                     390
#define TRAINER_MARIA_2                     391
#define TRAINER_MARIA_3                     392
#define TRAINER_MARIELA                     393
#define TRAINER_MARK                        394
#define TRAINER_MARLENE                     395
#define TRAINER_MARLEY                      396
#define TRAINER_MARTHA                      397
#define TRAINER_MARY                        398
#define TRAINER_MATTHEW                     399
#define TRAINER_MAURA                       400
#define TRAINER_MELINA                      401
#define TRAINER_MELISSA                     402
#define TRAINER_MEL_AND_PAUL                403
#define TRAINER_MICAH                       404
#define TRAINER_MICHELLE                    405
#define TRAINER_MIGUEL_1                    406
#define TRAINER_MIGUEL_2                    407
#define TRAINER_MIGUEL_3                    408
#define TRAINER_MIKE_1                      409
#define TRAINER_MISSY                       410
#define TRAINER_MITCHELL                    411
#define TRAINER_MIU_AND_YUKI                412
#define TRAINER_MOLLIE                      413
#define TRAINER_MYLES                       414
#define TRAINER_NANCY                       415
#define TRAINER_NAOMI                       416
#define TRAINER_NATE                        417
#define TRAINER_NED                         418
#define TRAINER_NICHOLAS                    419
#define TRAINER_NICOLAS_1                   420
#define TRAINER_NICOLAS_2                   421
#define TRAINER_NICOLAS_3                   422
#define TRAINER_NIKKI                       423
#define TRAINER_NOB_1                       424
#define TRAINER_NOB_2                       425
#define TRAINER_NOB_3                       426
#define TRAINER_NOLAN                       427
#define TRAINER_NOLAND                      428
#define TRAINER_NOLEN                       429
#define TRAINER_OLIVIA                      430
#define TRAINER_OWEN                        431
#define TRAINER_PABLO_1                     432
#define TRAINER_PABLO_2                     433
#define TRAINER_PABLO_3                     434
#define TRAINER_PARKER                      435
#define TRAINER_PAT                         436
#define TRAINER_PATRICIA                    437
#define TRAINER_PAUL                        438
#define TRAINER_PAULA                       439
#define TRAINER_PAXTON                      440
#define TRAINER_PERRY                       441
#define TRAINER_PETE                        442
#define TRAINER_PHIL                        443
#define TRAINER_PHILLIP                     444
#define TRAINER_PRESLEY                     445
#define TRAINER_PRESTON                     446
#define TRAINER_QUINCY                      447
#define TRAINER_RACHEL                      448
#define TRAINER_RANDALL                     449
#define TRAINER_REED                        450
#define TRAINER_RELI_AND_IAN                451
#define TRAINER_REYNA                       452
#define TRAINER_RHETT                       453
#define TRAINER_RICHARD                     454
#define TRAINER_RICK                        455
#define TRAINER_RICKY_1                     456
#define TRAINER_RICKY_2                     457
#define TRAINER_RICKY_3                     458
#define TRAINER_RILEY                       459
#define TRAINER_ROBERT_1                    460
#define TRAINER_ROBERT_2                    461
#define TRAINER_ROBERT_3                    462
#define TRAINER_ROBIN                       463
#define TRAINER_RODNEY                      464
#define TRAINER_ROGER                       465
#define TRAINER_ROLAND                      466
#define TRAINER_RONALD                      467
#define TRAINER_ROSE_1                      468
#define TRAINER_ROSE_2                      469
#define TRAINER_ROSE_3                      470
#define TRAINER_RUBEN                       471
#define TRAINER_SALLY                       472
#define TRAINER_SAMANTHA                    473
#define TRAINER_SAMUEL                      474
#define TRAINER_SANTIAGO                    475
#define TRAINER_SARAH                       476
#define TRAINER_SAWYER_1                    477
#define TRAINER_SAWYER_2                    478
#define TRAINER_SAWYER_3                    479
#define TRAINER_SEBASTIAN                   480
#define TRAINER_SHANE                       481
#define TRAINER_SHANNON                     482
#define TRAINER_SHARON                      483
#define TRAINER_SHAWN                       484
#define TRAINER_SHAYLA                      485
#define TRAINER_SHEILA                      486
#define TRAINER_SHELBY_1                    487
#define TRAINER_SHELBY_2                    488
#define TRAINER_SHELBY_3                    489
#define TRAINER_SHIRLEY                     490
#define TRAINER_SIENNA                      491
#define TRAINER_SIMON                       492
#define TRAINER_SOPHIA                      493
#define TRAINER_SOPHIE                      494
#define TRAINER_SPENCER                     495
#define TRAINER_SPENSER                     496
#define TRAINER_STAN                        497
#define TRAINER_STEVE_1                     498
#define TRAINER_STEVE_2                     499
#define TRAINER_STEVE_3                     500
#define TRAINER_SUSIE                       501
#define TRAINER_SYLVIA                      502
#define TRAINER_TAKAO                       503
#define TRAINER_TAKASHI                     504
#define TRAINER_TALIA                       505
#define TRAINER_TAMMY                       506
#define TRAINER_TANYA                       507
#define TRAINER_TARA                        508
#define TRAINER_TASHA                       509
#define TRAINER_TAYLOR                      510
#define TRAINER_TED                         511
#define TRAINER_TERRY                       512
#define TRAINER_THALIA_1                    513
#define TRAINER_THALIA_2                    514
#define TRAINER_THALIA_3                    515
#define TRAINER_THOMAS                      516
#define TRAINER_TIANA                       517
#define TRAINER_TIFFANY                     518
#define TRAINER_TIMMY                       519
#define TRAINER_TIMOTHY_1                   520
#define TRAINER_TIMOTHY_2                   521
#define TRAINER_TIMOTHY_3                   522
#define TRAINER_TISHA                       523
#define TRAINER_TOMMY                       524
#define TRAINER_TONY_1                      525
#define TRAINER_TONY_2                      526
#define TRAINER_TONY_3                      527
#define TRAINER_TORI_AND_TIA                528
#define TRAINER_TRAVIS                      529
#define TRAINER_TRENT_1                     530
#define TRAINER_TRENT_2                     531
#define TRAINER_TRENT_3                     532
#define TRAINER_TUCKER                      533
#define TRAINER_TYRA_AND_IVY                534
#define TRAINER_TYRON                       535
#define TRAINER_VALERIE_1                   536
#define TRAINER_VALERIE_2                   537
#define TRAINER_VALERIE_3                   538
#define TRAINER_VANESSA                     539
#define TRAINER_VICKY                       540
#define TRAINER_VICTOR                      541
#define TRAINER_VICTORIA                    542
#define TRAINER_VINCENT                     543
#define TRAINER_VIOLET                      544
#define TRAINER_VIRGIL                      545
#define TRAINER_VITO                        546
#define TRAINER_VIVI                        547
#define TRAINER_VIVIAN                      548
#define TRAINER_WADE                        549
#define TRAINER_WALTER_1                    550
#define TRAINER_WALTER_2                    551
#define TRAINER_WALTER_3                    552
#define TRAINER_WARREN                      553
#define TRAINER_WAYNE                       554
#define TRAINER_WENDY                       555
#define TRAINER_WILLIAM                     556
#define TRAINER_WILTON_1                    557
#define TRAINER_WILTON_2                    558
#define TRAINER_WILTON_3                    559
#define TRAINER_WINSTON_1                   560
#define TRAINER_WINSTON_2                   561
#define TRAINER_WINSTON_3                   562
#define TRAINER_WYATT                       563
#define TRAINER_YASU                        564
#define TRAINER_YUJI                        565
#define TRAINER_ZANDER                      566

#define TRAINER_GABBY_AND_TY_1              567
#define TRAINER_GABBY_AND_TY_2              568
#define TRAINER_GABBY_AND_TY_3              569
#define TRAINER_GABBY_AND_TY_4              570
#define TRAINER_GABBY_AND_TY_5              571
#define TRAINER_GABBY_AND_TY_6              572

#define TRAINER_GRUNT_PETALBURG_WOODS       573
#define TRAINER_GRUNT_RUSTURF_TUNNEL        574
#define TRAINER_GRUNT_MUSEUM_1              575
#define TRAINER_GRUNT_MUSEUM_2              576
#define TRAINER_GRUNT_WEATHER_INST_1        577
#define TRAINER_GRUNT_WEATHER_INST_2        578
#define TRAINER_GRUNT_WEATHER_INST_3        579
#define TRAINER_GRUNT_WEATHER_INST_4        580
#define TRAINER_GRUNT_WEATHER_INST_5        581
#define TRAINER_GRUNT_MT_PYRE_1             582
#define TRAINER_GRUNT_MT_PYRE_2             583
#define TRAINER_GRUNT_MT_PYRE_3             584
#define TRAINER_GRUNT_MT_PYRE_4             585
#define TRAINER_GRUNT_AQUA_HIDEOUT_1        586
#define TRAINER_GRUNT_AQUA_HIDEOUT_2        587
#define TRAINER_GRUNT_AQUA_HIDEOUT_3        588
#define TRAINER_GRUNT_AQUA_HIDEOUT_4        589
#define TRAINER_GRUNT_AQUA_HIDEOUT_5        590
#define TRAINER_GRUNT_AQUA_HIDEOUT_6        591
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        592
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        593
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1     594
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2     595
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3     596
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4     597
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     598

#define TRAINER_SHELLY_WEATHER_INSTITUTE    599
#define TRAINER_MATT                        600
#define TRAINER_SHELLY_SEAFLOOR_CAVERN      601
#define TRAINER_ARCHIE                      602

#define TRAINER_GRUNT_MT_CHIMNEY_1          603
#define TRAINER_GRUNT_MT_CHIMNEY_2          604
#define TRAINER_GRUNT_JAGGED_PASS           605
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       606
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       607
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       608
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       609
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       610
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       611
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       612
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       613
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       614
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      615
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      616
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      617
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      618
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      619
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      620
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      621
#define TRAINER_GRUNT_SPACE_CENTER_1        622
#define TRAINER_GRUNT_SPACE_CENTER_2        623
#define TRAINER_GRUNT_SPACE_CENTER_3        624
#define TRAINER_GRUNT_SPACE_CENTER_4        625
#define TRAINER_GRUNT_SPACE_CENTER_5        626
#define TRAINER_GRUNT_SPACE_CENTER_6        627
#define TRAINER_GRUNT_SPACE_CENTER_7        628

#define TRAINER_TABITHA_MT_CHIMNEY          629
#define TRAINER_MAXIE_MT_CHIMNEY            630
#define TRAINER_TABITHA_MAGMA_HIDEOUT       631
#define TRAINER_MAXIE_MAGMA_HIDEOUT         632
#define TRAINER_TABITHA_MOSSDEEP            633
#define TRAINER_MAXIE_MOSSDEEP              634
#define TRAINER_WALLY_MAUVILLE              635
#define TRAINER_WALLY_VR_1                  636
#define TRAINER_WALLY_VR_2                  637
#define TRAINER_WALLY_VR_3                  638
#define TRAINER_WALLY_VR_4                  639
#define TRAINER_WALLY_VR_5                  640
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   641
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   642
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    643
#define TRAINER_MAY_ROUTE_103_MUDKIP        644
#define TRAINER_MAY_ROUTE_103_TREECKO       645
#define TRAINER_MAY_ROUTE_103_TORCHIC       646
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    647
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    648
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     649
#define TRAINER_MAY_RUSTBORO_TREECKO        650
#define TRAINER_MAY_RUSTBORO_TORCHIC        651
#define TRAINER_MAY_RUSTBORO_MUDKIP         652
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    653
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   654
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   655
#define TRAINER_MAY_ROUTE_110_MUDKIP        656
#define TRAINER_MAY_ROUTE_110_TORCHIC       657
#define TRAINER_MAY_ROUTE_110_TREECKO       658
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    659
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   660
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   661
#define TRAINER_MAY_ROUTE_119_MUDKIP        662
#define TRAINER_MAY_ROUTE_119_TORCHIC       663
#define TRAINER_MAY_ROUTE_119_TREECKO       664
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     665
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    666
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    667
#define TRAINER_MAY_LILYCOVE_MUDKIP         668
#define TRAINER_MAY_LILYCOVE_TORCHIC        669
#define TRAINER_MAY_LILYCOVE_TREECKO        670
#define TRAINER_ROXANNE_1                   671
#define TRAINER_ROXANNE_2                   672
#define TRAINER_ROXANNE_3                   673
#define TRAINER_ROXANNE_4                   674
#define TRAINER_ROXANNE_5                   675
#define TRAINER_BRAWLY_1                    676
#define TRAINER_BRAWLY_2                    677
#define TRAINER_BRAWLY_3                    678
#define TRAINER_BRAWLY_4                    679
#define TRAINER_BRAWLY_5                    680
#define TRAINER_WATTSON_1                   681
#define TRAINER_WATTSON_2                   682
#define TRAINER_WATTSON_3                   683
#define TRAINER_WATTSON_4                   684
#define TRAINER_WATTSON_5                   685
#define TRAINER_FLANNERY_1                  686
#define TRAINER_FLANNERY_2                  687
#define TRAINER_FLANNERY_3                  688
#define TRAINER_FLANNERY_4                  689
#define TRAINER_FLANNERY_5                  690
#define TRAINER_NORMAN_1                    691
#define TRAINER_NORMAN_2                    692
#define TRAINER_NORMAN_3                    693
#define TRAINER_NORMAN_4                    694
#define TRAINER_NORMAN_5                    695
#define TRAINER_WINONA_1                    696
#define TRAINER_WINONA_2                    697
#define TRAINER_WINONA_3                    698
#define TRAINER_WINONA_4                    699
#define TRAINER_WINONA_5                    701
#define TRAINER_TATE_AND_LIZA_1             702
#define TRAINER_TATE_AND_LIZA_2             703
#define TRAINER_TATE_AND_LIZA_3             704
#define TRAINER_TATE_AND_LIZA_4             705
#define TRAINER_TATE_AND_LIZA_5             706
#define TRAINER_JUAN_1                      707
#define TRAINER_JUAN_2                      708
#define TRAINER_JUAN_3                      709
#define TRAINER_JUAN_4                      710
#define TRAINER_JUAN_5                      711
#define TRAINER_SIDNEY                      712
#define TRAINER_PHOEBE                      713
#define TRAINER_GLACIA                      714
#define TRAINER_DRAKE                       715
#define TRAINER_WALLACE                     716
#define TRAINER_STEVEN                      717
#define TRAINER_RED                         718
#define TRAINER_LEAF                        719
#define TRAINER_BRENDAN_PLACEHOLDER         720
#define TRAINER_MAY_PLACEHOLDER             721
#define TRAINER_BRENDAN_ROUTE_103_POSTGAME  722
#define TRAINER_MAY_ROUTE_103_POSTGAME      723
#define TRAINER_META_BOY                    724

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      725
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
